-- by iElden
local LSM = LibStub("LibSharedMedia-3.0")

LSM:Register("sound", "|cfffe7b2cAlerte au gogol|r", [[Interface\Addons\EldenSound\sounds\alerte_au_gogol.ogg]])
LSM:Register("sound", "|cfffe7b2cAoe2 01 oui|r", [[Interface\Addons\EldenSound\sounds\aoe2_01_oui.ogg]])
LSM:Register("sound", "|cfffe7b2cAoe2 02 non|r", [[Interface\Addons\EldenSound\sounds\aoe2_02_non.ogg]])
LSM:Register("sound", "|cfffe7b2cAoe2 03 merci|r", [[Interface\Addons\EldenSound\sounds\aoe2_03_merci.ogg]])
LSM:Register("sound", "|cfffe7b2cAoe2 07 ahhhhh|r", [[Interface\Addons\EldenSound\sounds\aoe2_07_ahhhhh.ogg]])
LSM:Register("sound", "|cfffe7b2cAoe2 09 ouuuuuuuu|r", [[Interface\Addons\EldenSound\sounds\aoe2_09_ouuuuuuuu.ogg]])
LSM:Register("sound", "|cfffe7b2cAoe2 11 ahahahah|r", [[Interface\Addons\EldenSound\sounds\aoe2_11_ahahahah.ogg]])
LSM:Register("sound", "|cfffe7b2cAoe2 20 grandmere|r", [[Interface\Addons\EldenSound\sounds\aoe2_20_grandmere.ogg]])
LSM:Register("sound", "|cfffe7b2cAoe2 27 2heures|r", [[Interface\Addons\EldenSound\sounds\aoe2_27_2heures.ogg]])
LSM:Register("sound", "|cfffe7b2cAoe2 31 attacknow|r", [[Interface\Addons\EldenSound\sounds\aoe2_31_attacknow.ogg]])
LSM:Register("sound", "|cfffe7b2cAoe2 36 waittoattack|r", [[Interface\Addons\EldenSound\sounds\aoe2_36_waittoattack.ogg]])
LSM:Register("sound", "|cfffe7b2cCsgo bomb defused|r", [[Interface\Addons\EldenSound\sounds\csgo_bomb_defused.ogg]])
LSM:Register("sound", "|cfffe7b2cCsgo bomb planted|r", [[Interface\Addons\EldenSound\sounds\csgo_bomb_planted.ogg]])
LSM:Register("sound", "|cfffe7b2cDebout|r", [[Interface\Addons\EldenSound\sounds\debout.ogg]])
LSM:Register("sound", "|cfffe7b2cHallelujah|r", [[Interface\Addons\EldenSound\sounds\hallelujah.ogg]])
LSM:Register("sound", "|cfffe7b2cHiddenblade|r", [[Interface\Addons\EldenSound\sounds\hiddenblade.ogg]])
LSM:Register("sound", "|cfffe7b2cKo fortnite|r", [[Interface\Addons\EldenSound\sounds\ko_fortnite.ogg]])
LSM:Register("sound", "|cfffe7b2cLol rengar detect|r", [[Interface\Addons\EldenSound\sounds\lol_rengar_detect.ogg]])
LSM:Register("sound", "|cfffe7b2cLol volibear loop|r", [[Interface\Addons\EldenSound\sounds\lol_volibear_loop.ogg]])
LSM:Register("sound", "|cfffe7b2cLol volibear ult|r", [[Interface\Addons\EldenSound\sounds\lol_volibear_ult.ogg]])
LSM:Register("sound", "|cfffe7b2cLow hp pokemon|r", [[Interface\Addons\EldenSound\sounds\low_hp_pokemon.ogg]])
LSM:Register("sound", "|cfffe7b2cMisschat|r", [[Interface\Addons\EldenSound\sounds\misschat.ogg]])
LSM:Register("sound", "|cfffe7b2cMultiplex|r", [[Interface\Addons\EldenSound\sounds\multiplex.ogg]])
LSM:Register("sound", "|cfffe7b2cMusclor|r", [[Interface\Addons\EldenSound\sounds\musclor.ogg]])
LSM:Register("sound", "|cfffe7b2cNuke and bip|r", [[Interface\Addons\EldenSound\sounds\nuke_and_bip.ogg]])
LSM:Register("sound", "|cfffe7b2cNuke short|r", [[Interface\Addons\EldenSound\sounds\nuke_short.ogg]])
LSM:Register("sound", "|cfffe7b2cNul a chier|r", [[Interface\Addons\EldenSound\sounds\nul_a_chier.ogg]])
LSM:Register("sound", "|cfffe7b2cSee you again|r", [[Interface\Addons\EldenSound\sounds\see_you_again.ogg]])
LSM:Register("sound", "|cfffe7b2cTiltboubou|r", [[Interface\Addons\EldenSound\sounds\tiltboubou.ogg]])
LSM:Register("sound", "|cfffe7b2cTmntlowhp|r", [[Interface\Addons\EldenSound\sounds\tmntlowhp.ogg]])
LSM:Register("sound", "|cfffe7b2cTuforce|r", [[Interface\Addons\EldenSound\sounds\tuforce.ogg]])
LSM:Register("sound", "|cfffe7b2cZinedine|r", [[Interface\Addons\EldenSound\sounds\zinedine.ogg]])